app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, session, redirect, url_for, request, jsonify
from flask_login import login_required
from . import main
from ..models import FlaskyArticles


@main.route('/', methods=['GET'])
def index():
    page = request.args.get('page', type=int, default=1)
    limit = request.args.get('limit', type=int, default=5)
    filters = {
        FlaskyArticles.drafted == False,
        FlaskyArticles.published_at != None
    }
    pagination = FlaskyArticles.query.filter(*filters).order_by(
        FlaskyArticles.published_at.desc()).paginate(
            page, limit, False)
    articles = pagination.items
    return render_template('main/index.html', articles=articles, pagination=pagination)


@main.route('/article/<int:id>', methods=['GET'])
def article(id):
    article = FlaskyArticles.query.get_or_404(id)
    return render_template('main/article.html', article=article)

app/templates/main/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<div class="flex-left">
    <div class="unit">
        <a  class="btn btn-primary"
            href="{% if pagination.has_prev %}{{ url_for(endpoint,
            page = pagination.page - 1, **kwargs) }}{% else %}#{% endif %}"
            {% if pagination.has_prev %}{% else %}disabled{% endif %}>
            上一页
        </a>
    </div>
    <div>
        <a  class="btn btn-primary"
            href="{% if pagination.has_next %}{{ url_for(endpoint,
            page = pagination.page + 1, **kwargs) }}{% else %}#{% endif %}"
            {% if pagination.has_next %}{% else %}disabled{% endif %}>
            下一页
        </a>
    </div>
</div>
{% endmacro %}

app/templates/main/article.html
{%extends "main/base.html"%} {%block title%}{{article.title}}{%endblock%} {%block content%}
<figure>
    <h3 class="flex-center">{{article.title}}</h3>
    <figcaption class="flex-center">{{article.published_at}}</figcaption>
</figure>
<hr>
<div>{{article.content|safe}}</div>
{%endblock%}

app/templates/main/base.html
<!DOCYTPE HTML>
<html lang="en">

<head>
    {% block head %}
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8">
    <title>My - {%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/mobi.min.css')}}">
    <link rel="shortcut icon" type="image/x-icon" href="{{url_for('static', filename='images/favicon.ico')}}"> {% endblock %}
</head>

<body>
    <div class="flex-center">
        <div class="container">
            {%block content%} {%endblock%}
        </div>
    </div>
</body>

</html>

app/templates/main/index.html
{%extends "main/base.html"%}

{%import "main/_macros.html" as macros%} 

{%block title%}欢迎.{%endblock%} {%block content%} 

{%block head%} 
{{super()}}
<style>
    .article-container {
        cursor: pointer;
        color: #777;
    }

    .article-container:hover {
        color: #333;
    }
</style>
{%endblock%}

{%for article in articles %}
{%set name = url_for('main.article', id=article.id)%}
<section onclick="window.location.href='{{name}}'" class="article-container">
    <figure>
        <h3>{{article.title}}</h3>
        <figcaption>{{article.published_at}}</figcaption>
    </figure>
    <div>{{article.content|truncate(250)|safe}}</div>
</section>
<hr> 
{% endfor %}

{{macros.pagination_widget(pagination, 'main.index')}} 
{%endblock%}