app/console/__init__.py
from flask import Blueprint

console = Blueprint('console', __name__)

from . import views

app/console/views.py
import json
import os
import time
import hashlib
from datetime import datetime
from flask import render_template, request, flash, jsonify
from flask_login import login_required, current_user
from . import console
from .. import photos, db
from config import Config
from ..models import FlaskyArticles, FlaskyConfigs


# 后台首页
@console.route('/index', methods=['GET'])
@login_required
def index():
    return render_template('console/index.html')


# 文章列表页
@console.route('/article', methods=['GET'])
@login_required
def article_index():
    return render_template('console/article/index.html')


# 文章列表数据接口
@console.route('/article/list', methods=['GET'])
@login_required
def article_list():
    page = request.args.get('page', type=int, default=1)
    limit = request.args.get('limit', type=int, default=10)
    articles = FlaskyArticles.query.filter_by(drafted=False).paginate(
        page, limit, False).items
    count = FlaskyArticles.query.count()
    return jsonify({
        'code': 0,
        'msg': 'success',
        'count': count,
        'data': [article.to_json() for article in articles]
    })


# 文章图片素材上传接口
@console.route('/article/upload', methods=['POST'])
@login_required
def article_upload():
    data = []
    folder = datetime.now().strftime('%Y-%m-%d')
    dest_folder = Config.UPLOADED_PHOTOS_DEST + folder
    if 'photos' in request.files:
        for filename in request.files.getlist('photos'):
            hash_name = hashlib.md5(
                current_user.username.encode('utf-8') +
                str(time.time()).encode('utf-8')).hexdigest()[:15]
            if not os.path.isdir(dest_folder):
                os.makedirs(dest_folder)
            dest_name = photos.save(
                filename, folder=folder, name=hash_name + '.')
            data.append(photos.url(dest_name))
        return json.dumps({'errno': 0, 'data': data})
    return json.dumps({'errno': -1, 'data': data})


# 文章新增视图
@console.route('/article/new', methods=['GET', 'POST'])
@login_required
def article_create():
    if request.method == 'GET':
        return render_template('console/article/create.html')
    else:
        param = request.form.get('param', type=str, default=None)
        if param == 'publish':
            article = FlaskyArticles(
                title=request.form.get('title'),
                content=request.form.get('content').encode('utf-8'),
                published_at=datetime.utcnow())
        else:
            article = FlaskyArticles(
                title=request.form.get('title'),
                content=request.form.get('content'))
        db.session.add(article)
        db.session.commit()
        #flash('文章创建成功')
        return json.dumps({'ret_code': 0, 'ret_msg': 'success'})


# 文章修改视图
@console.route('/article/show/<int:id>', methods=['GET'])
@login_required
def article_show(id):
    article = FlaskyArticles.query.get_or_404(id)
    return render_template('console/article/show.html', article=article)


# 文章更新接口
@console.route('/article/update', methods=['POST'])
@login_required
def article_update():
    id = request.form.get('id', type=int, default=None)
    article = FlaskyArticles.query.get_or_404(id)
    if article is None:
        return json.dumps({'ret_code': -1, 'ret_msg': 'fail'})
    param = request.form.get('param', type=str, default=None)
    article.title = request.form.get('title')
    article.content = request.form.get('content').encode('utf-8')
    article.updated_at = datetime.utcnow()
    if param == 'publish':
        article.published_at = datetime.utcnow()
    db.session.add(article)
    db.session.commit()
    #flash('文章修改成功')
    return json.dumps({'ret_code': 0, 'ret_msg': 'success'})


# 文章删除接口
@console.route('/article/delete', methods=['POST'])
@login_required
def article_delete():
    id = request.form.get('id')
    article = FlaskyArticles.query.filter_by(id=id).first()
    if article is None:
        return jsonify({'ret_code': -1, 'ret_msg': 'faield'})
    article.drafted = True
    article.updated_at = datetime.utcnow()
    db.session.add(article)
    db.session.commit()
    return jsonify({'ret_code': 0, 'ret_msg': 'success'})


# 素材首页
@console.route('/album', methods=['GET'])
@login_required
def album_index():
    return render_template('console/material/index.html')


# 个人中心首页
@console.route('/my', methods=['GET', 'POST'])
@login_required
def my():
    if request.method == 'GET':
        return render_template('console/my/index.html')
    else:
        return json.dumps({'ret_code':0, 'ret_msg': 'success'})

app/templates/console/article/create.html
<!DOCYTPE HTML>
<html lang="en">

<head>
    {% block head %}
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8">
    <title>好记性不如烂笔头 - Pretty Flasky</title>
    <link href="{{url_for('static', filename='css/index.css')}}" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="{{url_for('static', filename='images/favicon.ico')}}">
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='wangEditor/release/wangEditor.min.js')}}"></script>
    {% endblock %}

</head>

<body>
    <div id="article">
        <div id="title">
            <input type="text" placeholder="输入标题" id="article-title">
        </div>
        <div id="editor-toolbar" class="editor-toolbar"></div>
        <div id="editor-content" class="editor-content"></div>
        <div id="btn-groups">
            <button id="publish-btn" style="margin-left: 20px;" type="button">发布</button>
            <button id="save-btn" class="default-btn" type="button">保存</button>
        </div>
    </div>

    <script type="text/javascript">
        var E = window.wangEditor;
        var editor = new E('#editor-toolbar', '#editor-content');
        // 设置富文本编辑器z-index
        editor.customConfig.zIndex = 100;
        // 关闭粘贴样式的过滤
        editor.customConfig.pasteFilterStyle = false;
        // 上传图片服务端接口配置
        editor.customConfig.uploadImgServer = '{{url_for("console.article_upload")}}';
        // 上传图片 filename
        editor.customConfig.uploadFileName = 'photos';
        // 错误提示
        editor.customConfig.customAlert = function (info) {
            console.log(info);
        }
        // 通过 url 参数配置 debug 模式。url 中带有 editor_debug_mode=1 才会开启 debug 模式
        editor.customConfig.debug = location.href.indexOf('editor_debug_mode=1') > 0
        editor.create();
    </script>

    <script type="text/javascript">
        $(function () {
            $('#publish-btn').on('click', function () {
                create_new_article('publish');
            });
            $('#save-btn').on('click', function () {
                create_new_article('save');
            });

            function create_new_article(param){
                var title = $('#article-title').val().trim();
                if(!title){
                    return false;
                }
                var content = editor.txt.html();
                $.post('{{url_for("console.article_create")}}', {
                    title: title,
                    content: content,
                    param: param
                }, function(response){
                    var res = JSON.parse(response);
                    if(res.ret_code === 0){
                        window.location.href = '{{url_for("console.article_index")}}';
                    }
                });
            }
        });
    </script>

</body>

</html>

app/templates/console/article/index.html
{% extends "console/base.html" %} {% block content %}
<fieldset class="layui-elem-field">
    <legend>文章列表</legend>
    <div class="layui-field-box">
        <a class="layui-btn" href="{{url_for('console.article_create')}}">创建文章</a>
    </div>
</fieldset>
<table class="layui-table" id="table-list" lay-filter="article-list"></table>

<script type="text/html" id="toolbar">
    <a class="layui-btn layui-btn-mini" lay-event="edit">查看</a>
    <a class="layui-btn layui-btn-danger layui-btn-mini" lay-event="del">删除</a>
</script>

{% endblock %} {% block script %}
<script>
    layui.use('table', function () {

        var table = layui.table;
        var $ = layui.$;

        table.render({
            elem: '#table-list',
            url: '{{url_for("console.article_list")}}',
            width: '100%',
            height: 'full-320',
            page: true,
            limits: [10, 20, 30],
            limit: 10,
            cols: [[
                { field: 'id', width: 80, sort: true, title: '#' },
                { field: 'title', width: 200, edit: true, title: '标题' },
                { field: 'views', width: 80, sort: true, title: '查阅' },
                { field: 'created_at', width: 200, sort: true, title: '创建日期' },
                { field: 'published_at', width: 200, sort: true, title: '发布日期' },
                { fixed: 'right', width: 150, align: 'center', toolbar: '#toolbar', title: '操作' }
            ]]
        });

        table.on('tool(article-list)', function (obj) {
            var data = obj.data;
            var layEvent = obj.event;
            var tr = obj.tr;

            if (layEvent === 'del') {
                layer.confirm('确定删除操作?', function (index) {
                    layer.close(index);
                    $.post('{{url_for("console.article_delete")}}', { id: data.id }, function (response) {
                        if (response.ret_code === 0) {
                            obj.del();
                        } else {
                            layer.confirm('删除失败!', function (index) {
                                layer.close(index);
                            });
                        }
                    });
                })
            } else if (layEvent === 'edit') {
                window.location.href = data.link;
            } else {
                return false;
            }
        });

    });

</script>
{% endblock %}

app/templates/console/article/show.html
<!DOCYTPE HTML>
<html lang="en">

<head>
    {% block head %}
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8">
    <title>好记性不如烂笔头 - Pretty Flasky</title>
    <link href="{{url_for('static', filename='css/index.css')}}" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="{{url_for('static', filename='images/favicon.ico')}}">
    <script type="text/javascript" src="{{url_for('static', filename='js/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{url_for('static', filename='wangEditor/release/wangEditor.min.js')}}"></script>
    {% endblock %}

</head>

<body>
    <div id="article">
        <div id="title">
            <input type="text" placeholder="输入标题" id="article-title" value="{{article.title}}">
        </div>
        <div id="editor-toolbar" class="editor-toolbar"></div>
        <div id="editor-content" class="editor-content">
            {{article.content|safe}}
        </div>
        <div id="btn-groups">
            <button id="publish-btn" style="margin-left: 20px;" type="button">发布</button>
            <button id="save-btn" class="default-btn" type="button">保存</button>
        </div>
    </div>

    <script type="text/javascript">
        var E = window.wangEditor;
        var editor = new E('#editor-toolbar', '#editor-content');
        // 设置富文本编辑器z-index
        editor.customConfig.zIndex = 100;
        // 关闭粘贴样式的过滤
        editor.customConfig.pasteFilterStyle = false;
        // 上传图片服务端接口配置
        editor.customConfig.uploadImgServer = '{{url_for("console.article_upload")}}';
        // 上传图片 filename
        editor.customConfig.uploadFileName = 'photos';
        // 错误提示
        editor.customConfig.customAlert = function (info) {
            console.log(info);
        }
        // 通过 url 参数配置 debug 模式。url 中带有 editor_debug_mode=1 才会开启 debug 模式
        editor.customConfig.debug = location.href.indexOf('editor_debug_mode=1') > 0
        editor.create();
    </script>

    <script type="text/javascript">
        $(function () {
            $('#publish-btn').on('click', function () {
                create_new_article('publish');
            });
            $('#save-btn').on('click', function () {
                create_new_article('save');
            });

            function create_new_article(param){
                var title = $('#article-title').val().trim();
                if(!title){
                    return false;
                }
                var content = editor.txt.html();
                $.post('{{url_for("console.article_update")}}', {
                    id: '{{article.id}}',
                    title: title,
                    content: content,
                    param: param
                }, function(response){
                    var res = JSON.parse(response);
                    if(res.ret_code === 0){
                        window.location.href = '{{url_for("console.article_index")}}';
                    }
                });
            }
        });
    </script>

</body>

</html>